spring:
  application:
    name: myntra-product-service    
  data:
    mongodb:
      database: ${productdb.database}
      uri: ${productdb.uri}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enabled: true
    
server:
  port: 8070
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
